### ISSUE TITLE
Allow lock holder to renew lock before it expires

### ISSUE THREAD

**Issue by thenewguy** [vikingco/django-locking#6]
Right now, a lock must expire before it can be renewed as read from https://github.com/vikingco/django-locking/blob/master/locking/models.py#L58

For my use case it would be preferable to allow the lock holder to renew the lock before it expires to prevent from losing the lock resulting in duplicate action.

**Comment by thenewguy** [comment]
Although I guess there is nothing stopping a manual update on the lock instance.  It would just be handy if it was automatic using the interface already provided

**Comment by nielsvanoch** [comment]
Fixed in 1.1.0.
